language: python
sudo: false
dist: trusty
python:
    - "3.6"
install:
    - pip3 install -r requirements.txt
script:
    - python3 -m pytest
    - bash -x testall.sh
before_install:
    - ip addr show
    - ls /proc/net
    - cat /proc/net/if_inet6
#    - ip addr show dev lo | grep -q inet6 || (echo "No IPv6 address found"; exit 1)
