language: python
python:
    - "3.6"
install:
    - pip3 install -r requirements.txt
script:
    - python3 -m pytest
    - bash -x testall.sh
    - python client-simple.py
    - python client-twisted.py
